spring:
  profiles:
    active: dev
  datasource:
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
  data:
    jpa:
      repositories:
        enabled: true
servlet_url: /tj/*
target_url: http://report.cdkjt.com.cn
static_servlet_url: /anyrt/*
static_target_url: http://report.cdkjt.com.cn/anyrt
report_servlet_url: /report/*
report_target_url: http://report.cdkjt.com.cn/report
demo_servlet_url: /demo/*
demo_target_url: http://127.0.0.1:8080/proxy